import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import config from "../siteConfig.json";
import { parseCssVariables } from "./utils";

import "./globals.css";

const palette = parseCssVariables(config.cssVariables || {}); // TODO: need to rethink method how we apply variables

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        style={palette}
        className={`${geistSans.variable} ${geistMono.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
